// Application main form file.

// Original file name: App_KaiXinMainForm.h
// Generated by TOPS Builder:Project wizard,Date:2010-8-24



#ifndef  __App_KaiXin_MainForm_H__
#define  __App_KaiXin_MainForm_H__
#include "TG3.h"

class TMainForm : public TWindow
{
public:

	TMainForm(TApplication * pApp);

	~TMainForm(void);

public:
	virtual Boolean EventHandler(TApplication * pApp, EventType * pEvent);
protected:
	void  _OnWinInitEvent();
	Boolean _OnCtlSelectEvent( TApplication * pApp,EventType * pEvent );
	Boolean _OnLstPreDrawEvent(EventType * pEvent);
	Boolean _OnCtrlSetFocusEvent(TApplication * pApp, EventType * pEvent);
	Boolean _OnCtrlKillFocusEvent(TApplication * pApp, EventType * pEvent);
private:
	//退出按钮ID
	Int32 m_ExitBtn;
	Int32 m_LoginBtn;
	//第一次点击显示密码是否需要清空密码
	Boolean bCleanPwdWhenFirstShowPwd;
};


#endif

