// Application application header file.

// Original file name: App_KaiXinApp.h
// Generated by TOPS Builder:Project wizard,Date:2010-8-24


#ifndef  __App_KaiXin_App_H__
#define  __App_KaiXin_App_H__
#include "TG3.h"
#include "TCOM_ConnectManager_Interface.h"
#include "TCOM_ConnectManager_DataType.h"

class  TApp_KaiXinApp  :  public  TApplication
{
public:
	TApp_KaiXinApp();
	~TApp_KaiXinApp();
	virtual Boolean EventHandler(EventType * pEvent);
	ULONG GetConnectID();
protected:
private:
	void ClosePanelForm(void);
	/** 连接管理器接口指针 */
	TCOM_ConnectManager_Interface *m_pConnectManger;
	/** 拨号连接ID */
	ULONG m_uConnectID;
	CM_ACCOUNT_ID_t m_tAID;	
	
	/** 欢迎画面等待定时器 */
	Int32 m_nTimerId;	

	//定时消息消息的定时器ID
	Int32 m_nMsgTimerId;

	/*初始化Form ID*/
	Int32 gHwndId_Init;

	/*登录Form ID*/
	Int32 gHwndId_Login;

	/*下载等待Form ID*/
	Int32 gHwndId_WaitingBox;
	
	//是否拨号成功后,在使用过程中被断开了
	Boolean m_bReConnected;

	Boolean  m_bConnected;	//是否已经连接成功
	//对应API的窗口是否有效
	Boolean FormIsValid(Int32  nAccessType);

	/*更新新消息条数*/
	int UpdateNoticeCount(void);
};


#endif

