// Application main file.
 
// Original file name: App_KaiXinEntry.cpp
// Generated by TOPS Builder:Project wizard,Date:2010-8-24
 
/*!
* 
* \file   App_KaiXinEntry.cpp
* \author GoZone
* \date	  2011-1-28
* \brief  应用入口
* 
* \ref    CopyRight
*/

 
#include  "App_KaiXinEntry.h"
#include  "App_KaiXinApp.h"
#include "TResolution.h"     
#if defined(UPHONE_HVGA)     
#include "Res_HVGA/app_kaixin_res_c.h"     
#elif defined(UPHONE_WVGA)     
#include "Res_WVGA/app_kaixin_res_c.h"     
#else     
#error resolution     
#endif 

const  ResourceRegisterEntry		ResRegList_App_KaiXin[]  =
{
	TG_RESOURCE_DEFINE
};

const  AppResourceEntry		App_KaiXinResourceEntry  =
{
	(ResourceRegisterEntry*)ResRegList_App_KaiXin,                    //  res  list  in  this  app
		sizeof(ResRegList_App_KaiXin) /  sizeof(ResourceRegisterEntry),    //number  of  item  in  res
};

Int32 TG3AppMain(const TUChar * pAppID, UInt32 nCmd, void * pCmdParam)
{
	switch(nCmd)
	{
	case 0: // 主入口
		{
			// UI应用程序例子：
			TApp_KaiXinApp  *  pApp= new  TApp_KaiXinApp();
			pApp->WM_SetResourceEntry(&App_KaiXinResourceEntry);
			pApp->Run();

			delete pApp;
			break;
		}
	}
	return 1;
}


