// Application application header file.

// Original file name: App_KaiXinAPI.h
// Generated by TOPS Builder:Project wizard,Date:2010-8-24


#ifndef  __TestForm_H__
#define  __TestForm_H__
#include "TG3.h"

class TestForm : public TWindow
{
public:
	TestForm( TApplication *pApp );
	virtual Boolean EventHandler( TApplication * pApp, EventType * pEvent );
private:
	// define private method here
	Boolean _OnWinInitEvent(TApplication * pApp, EventType * pEvent);
	Boolean _OnCtlSelectEvent(TApplication * pApp, EventType * pEvent);

private:
	// define private data member here
};


#endif