/*!
*@FileName: KaiXinApp_PhotoDetail.h
*@Author: GoZone
*@Date:
*@Log: 	Author 			Date 		Description
*
*@section Copyright
* =======================================================================<br>
*          Copyright ? 2010-2012 GOZONE <br>
*                All Rights Reserved.<br>
* The file is generated by Kaixin_Component Wizard for Tranzda Mobile Platform <br>
* =======================================================================<br>
*/

#ifndef  __KAIXINAPI_PHOTODETAIL_H__
#define  __KAIXINAPI_PHOTODETAIL_H__

#include "KaiXinAPI.h"

typedef struct
{
	int dataFrom; //0: from albumPhoto, 1: from updatefriendsnews
	char photouid[32]; 	  //照片所属用户id
	char fname[64];
	char pid[32];
	char title[256];
	char thumbnail[256];
	char large[256];
	char privacy[8];
	char albumid[32];
	char albumtitle[256];
	char picnum[32];
	int pos;
	int ctime;
	char ctimeString[32];	
	int cnum;
}tPhotoDetail;

typedef enum
{
	KX_PrePhoto,			
	KX_NextPhoto = 1,		

	KX_ViewPhotoTypeEnd,
}KX_ViewPhotoType;


class TPhotoDetailForm : public TWindow
{
public:
	TPhotoDetailForm(TApplication* pApp);
	TPhotoDetailForm(TApplication* pApp, tPhotoDetail photodata);	
	virtual ~TPhotoDetailForm(void);
	virtual Boolean EventHandler(TApplication * appP, EventType * eventP);

private:
	Boolean _OnWinInitEvent(TApplication * pApp, EventType * pEvent);
	Boolean _OnWinClose(TApplication * pApp, EventType * pEvent);
	Boolean _OnCtrlSelectEvent(TApplication * pApp, EventType * pEvent);
	Int32 _SetTilteButton(TApplication * pApp);	
	Int32 _SetFormTilte(TApplication * pApp);
	Int32 _SetCtrlsStyle(TApplication* pApp);		
	Int32 _SetCtrlsData(TApplication* pApp);	
	Int32 _ViewPhoto(TApplication* pApp, KX_ViewPhotoType ViewType);
	Int32 _SetViewButtonEnabled(Boolean bEnabled);
	//Int32 _CreatePhotoImage(TApplication* pApp);

private:
	tPhotoDetail m_photodata;

	//图片
	TBitmap* pPhotoBmp;
	Int32 m_nAlbumPhotoCount;

	Int32 m_TitleButtonCtlID;//标题按钮, 显示专辑或者照片

	Int32 m_BackBtn;
};

#endif
