/*!
*@FileName: KaiXinApp_GardenDetail.h
*@Author: huxianxiang@GoZone
*@Date: 2010-9-29
*@Log: 	Author 			Date 		Description
*
*@section Copyright
* =======================================================================<br>
*          Copyright ? 2010-2012 GOZONE <br>
*                All Rights Reserved.<br>
* The file is generated by Kaixin_Component Wizard for Tranzda Mobile Platform <br>
* =======================================================================<br>
*/

#ifndef  __KAIXINAPI_GARDENDETAIL_H__
#define  __KAIXINAPI_GARDENDETAIL_H__

#include "KaiXinAPI.h"

typedef struct
{
	int cropsid;
	int farmnum;
	char name[32*3 + 1];
	char growper[32*3 + 1];
	char growdesc[64*3 + 1];
	int status;
	char shared[12];
	char sharename[8*3 + 1];
	int stealed;
	int htime;
	int isexpo;
}GardenDetail_crops;

typedef struct
{
	int ret;
	char uid[16 + 1];
	int nNum;
	char szCash[64 + 1];
	int cash;
	int ranktip;
	int tcharms;
	char fuid[16 + 1];
	char flogo[128*3 + 1];
	char fname[32*3 + 1];
	int  nSize_crops;  //Save the array size by code_gen tools. 
	GardenDetail_crops*  crops;
}tResponseGardenDetail;


extern void* KaiXinAPI_GardenDetail_JsonParse(char *text);


typedef struct
{
	char uid[32 + 1];
	int ret;
	char retdesc[1024*3 + 1];
}tResponseGardenHarvest;

extern void* KaiXinAPI_GardenHarvest_JsonParse(char *text);



class TGardenDetailForm : public TWindow
{
public:
	TGardenDetailForm(TApplication* pApp, Boolean bNew = TRUE);
	virtual ~TGardenDetailForm(void);
	virtual Boolean EventHandler(TApplication * appP, EventType * eventP);

private:
	Boolean _OnWinInitEvent(TApplication * pApp, EventType * pEvent);
	Boolean _OnWinClose(TApplication * pApp, EventType * pEvent);
	Boolean _OnCtrlSelectEvent(TApplication * pApp, EventType * pEvent);
	Int32 _SetFormTilte(TApplication * pApp);

private:
	tResponseGardenDetail* Response;

	Int32 nDetailItems;     //存储详情个数
	Int32 nActionId[10000];//存储收获，或者播种ID

	Int32 nGardenListViewId;//存储查看好友花园列表ID
	Int32 nMyGardenViewId;//返回查看我的花园
	Boolean IsSelf;
	char Fuid[32];

	Int32	m_BackBtn;
};

#endif