/*!
*@FileName: KaiXinApp_RecordList.h
*@Author: GoZone
*@Date:
*@Log: 	Author 			Date 		Description
*
*@section Copyright
* =======================================================================<br>
*          Copyright ? 2010-2012 GOZONE <br>
*                All Rights Reserved.<br>
* The file is generated by Kaixin_Component Wizard for Tranzda Mobile Platform <br>
* =======================================================================<br>
*/

#ifndef  __KAIXINAPI_RECORDLIST_H__
#define  __KAIXINAPI_RECORDLIST_H__

#include "KaiXinAPI.h"

typedef struct
{
	char rid[16+1];
	int ctime;
	char strctime[32];
	char content[1024];
	int commentnum;
	int upnum;
}RecordList_recordlist;

typedef struct
{
	int ret;
	char uid[32];
	int n;
	char total[16];
	int  nSize_recordlist;  //Save the array size by code_gen tools. 
	RecordList_recordlist*  recordlist;
}tResponseRecordList;


extern void* KaiXinAPI_RecordList_JsonParse(char *text);

#endif