/*!
*@FileName: KaiXinApp_Notice.h
*@Author: pengzhixiong@GoZone
*@Date: 2010-11-4
*@Log: 	Author 			Date 		Description
*
*@section Copyright
* =======================================================================<br>
*          Copyright ? 2010-2012 GOZONE <br>
*                All Rights Reserved.<br>
* The file is generated by Kaixin_Component Wizard for Tranzda Mobile Platform <br>
* =======================================================================<br>
*/

#ifndef  __KAIXINAPI_NOTICE_H__
#define  __KAIXINAPI_NOTICE_H__

#include "KaiXinAPI.h"

typedef struct
{
	int mtype;
	int n;
}Notice_notices;

typedef struct
{
	int ret;
	int n;
	int  nSize_notices;  //Save the array size by code_gen tools. 
	Notice_notices*  notices;
}tResponseNotice;


extern void* KaiXinAPI_Notice_JsonParse(char *text);


#endif