/*!
*@FileName: KaiXinApp_RepasteDetail.h
*@Author: huxianxiang@GoZone
*@Date: 2010-9-30
*@Log: 	Author 			Date 		Description
*
*@section Copyright
* =======================================================================<br>
*          Copyright ? 2010-2012 GOZONE <br>
*                All Rights Reserved.<br>
* The file is generated by Kaixin_Component Wizard for Tranzda Mobile Platform <br>
* =======================================================================<br>
*/

#ifndef  __KAIXINAPI_REPASTEDETAIL_H__
#define  __KAIXINAPI_REPASTEDETAIL_H__

#include "KaiXinAPI.h"
#include "TCOM_TBrowser_WebPanel.h"

typedef struct
{
	int ret;
	char uid[16];
}tResponsePostRepaste;

typedef struct
{
	int uid;
	char fname[32*3 + 1];
}RepasteDetail_repasters;

typedef struct
{
	int uid;
	char fname[32*3 + 1];
}RepasteDetail_visitors;

typedef struct
{
	int id;
	char name[128*3 + 1];
}RepasteDetail_taglist;

typedef struct
{
	int uid;
	char fname[32*3 + 1];
	char answer[32*3 + 1];
}RepasteDetail_resultlist;

typedef struct
{
	int votepercent;
	char answer[32*3 + 1];
	char votenum[16*3 + 1];
}RepasteDetail_answerlist;

typedef struct
{
	int ret;
	char uid[16 + 1];
	char surpid[16 + 1];//源转帖ID
	char urpid[16 + 1];//转帖ID
	char suid[16+1];//转帖用户ID
	char voteuid[16 + 1];//源转帖用户ID
	char title[128*3 + 1];
	char content[10000*3 + 1];
	char rpnum[16 + 1];
	char vnum[16+1];
	int  nSize_repasters;  //Save the array size by code_gen tools. 
	RepasteDetail_repasters*  repasters;	//好友转帖
	int  nSize_visitors;  //Save the array size by code_gen tools. 
	RepasteDetail_visitors*  visitors;	//好友浏览
	int  nSize_taglist;  //Save the array size by code_gen tools. 
	RepasteDetail_taglist*  taglist;		//标签列表
	char cnum[16 + 1];	//评论数
	int newflag;
	int  nSize_resultlist;  //Save the array size by code_gen tools. 
	RepasteDetail_resultlist*  resultlist;	//好友观点
	int  nSize_answerlist;  //Save the array size by code_gen tools. 
	RepasteDetail_answerlist*  answerlist;//固定观点
}tResponseRepasteDetail;


extern void* KaiXinAPI_RepasteDetail_JsonParse(char *text);
extern void* KaiXinAPI_PostRepaste_JsonParse(char * text);

class TRepasteDetailForm : public TWindow
{
public:
	TRepasteDetailForm(TApplication* pApp);
	virtual ~TRepasteDetailForm(void);
	virtual Boolean EventHandler(TApplication * appP, EventType * eventP);

private:
	Boolean _OnWinInitEvent(TApplication * pApp, EventType * pEvent);
	Boolean _OnWinClose(TApplication * pApp, EventType * pEvent);
	Boolean _OnCtrlSelectEvent(TApplication * pApp, EventType * pEvent);
	Int32 _SetFormTilte(TApplication * pApp);

	TBrowser::TWebPanel* m_pWebPanel;
	//TImage* 			 m_pVote;
	//TImage* 			 m_pComment;
	//TImage*  			 m_pRepaste;
	Int32 				 n_CommentCount;

	Int32	m_BackBtn;	
};

#endif