/*!
*@FileName: KaiXinApp_More.h
*@Author: GoZone
*@Date:
*@Log: 	Author 			Date 		Description
*
*@section Copyright
* =======================================================================<br>
*          Copyright ? 2010-2012 GOZONE <br>
*                All Rights Reserved.<br>
* The file is generated by Kaixin_Component Wizard for Tranzda Mobile Platform <br>
* =======================================================================<br>
*/

#ifndef  __KAIXINAPI_MORE_H__
#define  __KAIXINAPI_MORE_H__

#include "KaiXinAPI.h"

typedef struct
{
	int ret;
	int uid;
}tResponseMore;

typedef enum //MoreList
{
	KX_MoreType_Start,
	//KX_More_GiftList = 1,
	KX_More_FeedBack = 1,
	KX_More_Settings,
	KX_More_About,
	KX_More_Logout,

	KX_MoreType_END,
} KX_MoreType;
extern void* KaiXinAPI_More_JsonParse(char *text);

class TMoreForm : public TWindow
{
public:
	TMoreForm(TApplication* pApp);
	virtual ~TMoreForm(void);
	virtual Boolean EventHandler(TApplication * appP, EventType * eventP);

private:
	Boolean _OnWinInitEvent(TApplication * pApp, EventType * pEvent);
	Boolean _OnWinClose(TApplication * pApp, EventType * pEvent);
	Boolean _OnCtrlSelectEvent(TApplication * pApp, EventType * pEvent);
	Int32 SetTilteButton(TApplication * pApp);	
	Int32 SetFormTilte(TApplication * pApp);		
	Int32 _CreateTabButtons(TApplication* pApp);

private:
	//control 
	Int32 m_iaCreateCtlID[56];
	TCtrl *m_obContrl[56];
	Int32 m_nCtlIDCount;

	Int32 m_nNewsBtnID;//动态
	Int32 m_nFriendsBtnID;//好友
	Int32 m_nInfosBtnID;//我的地盘
	Int32 m_nAppsBtnID;//组件
	Int32 m_nMoreBtnID;//更多

	//退出按钮ID
	Int32 m_ExitBtn;
	//刷新按钮ID
	Int32 m_RefreshBtn;	
};

#endif