/*!
*@FileName: KaiXinApp_StatusFaceList.h
*@Author: GoZone
*@Date:
*@Log: 	Author 			Date 		Description
*
*@section Copyright
* =======================================================================<br>
*          Copyright ? 2010-2012 GOZONE <br>
*                All Rights Reserved.<br>
* The file is generated by Kaixin_Component Wizard for Tranzda Mobile Platform <br>
* =======================================================================<br>
*/

#ifndef  __KAIXINAPI_STATUSFACELIST_H__
#define  __KAIXINAPI_STATUSFACELIST_H__

#include "KaiXinAPI.h"

typedef struct
{
	int sface;
	char slogo[256];
	int ntype;
}StatusFaceList_faces;

typedef struct
{
	int ret;
	int uid;
	int n;
	int  nSize_faces;  //Save the array size by code_gen tools. 
	StatusFaceList_faces*  faces;
}tResponseStatusFaceList;


extern void* KaiXinAPI_StatusFaceList_JsonParse(char *text);

class TStatusFaceListForm : public TWindow
{
public:
	TStatusFaceListForm(TApplication* pApp);
	virtual ~TStatusFaceListForm(void);
	virtual Boolean EventHandler(TApplication * appP, EventType * eventP);

private:
	Boolean _OnWinInitEvent(TApplication * pApp, EventType * pEvent);
	Boolean _OnWinClose(TApplication * pApp, EventType * pEvent);
	Boolean _OnCtrlSelectEvent(TApplication * pApp, EventType * pEvent);
};

#endif