/*!
*@FileName: KaiXinApp_VoteDetail.h
*@Author: GoZone
*@Date:
*@Log: 	Author 			Date 		Description
*
*@section Copyright
* =======================================================================<br>
*          Copyright ? 2010-2012 GOZONE <br>
*                All Rights Reserved.<br>
* The file is generated by Kaixin_Component Wizard for Tranzda Mobile Platform <br>
* =======================================================================<br>
*/

#ifndef  __KAIXINAPI_VOTEDETAIL_H__
#define  __KAIXINAPI_VOTEDETAIL_H__

#include "KaiXinAPI.h"

//投票选项最大条数
#define KX_VOTE_ITEM_COUNT_MAX		(50)//假设投票最大条数为50

typedef struct
{
	char limit[32];
}VoteDetail_limitlist;

typedef struct
{
	char answer[128];
	char votenum[32];
	int votepercent;
}VoteDetail_answerlist;

typedef struct
{
	char uid[32];
	char fname[32];
	char ctime[32];
	char answer[60];
}VoteDetail_resultlist;

typedef struct
{
	int ret;
	int uid;
	char fname[32];
	char ctime[24];
	char endtime[32];
	char title[256];
	char votenum[32];
	int  nSize_limitlist;  //Save the array size by code_gen tools. 
	VoteDetail_limitlist*  limitlist;
	int  nSize_answerlist;  //Save the array size by code_gen tools. 
	VoteDetail_answerlist*  answerlist;
	int  nSize_resultlist;  //Save the array size by code_gen tools. 
	VoteDetail_resultlist*  resultlist;
	char intro[1024];
}tResponseVoteDetail;


extern void* KaiXinAPI_VoteDetail_JsonParse(char *text);

class TVoteDetailForm : public TWindow
{
public:
	TVoteDetailForm(TApplication* pApp);
	virtual ~TVoteDetailForm(void);
	virtual Boolean EventHandler(TApplication * appP, EventType * eventP);

private:
	Boolean _OnWinInitEvent(TApplication * pApp, EventType * pEvent);
	Boolean _OnWinClose(TApplication * pApp, EventType * pEvent);
	Boolean _OnCtrlSelectEvent(TApplication * pApp, EventType * pEvent);
	Int32 _GetLimitCount(TUChar* pLimit);

private:
	Int32 nVoteButtonId; //Use to save Vote Button ID	
	Int32 nVoteItemCount; //记录投票真实个数
	Int32 nVoteLimitCount; //投票限制个数
	Int32 nVoteSelectedImgId[KX_VOTE_ITEM_COUNT_MAX]; //Use to save Selected Image ID	
	Boolean IsVoteItemSelected[KX_VOTE_ITEM_COUNT_MAX]; //Use to save whether the vote item is selected or not
	Int32 nVoteSelectedCount; //已经选择的投票个数

	Int32	m_BackBtn;
};

#endif