/*!
* \file	 KaiXinAPI_MessageDetail.cpp
* \author	 huxianxiang@GoZone
* \date	 2010-11-8
* \brief  解析与UI: 消息详情
*
* \ref    CopyRight
* =======================================================================<br>
*          Copyright ? 2010-2012 GOZONE <br>
*                All Rights Reserved.<br>
* The file is generated by Kaixin_Component Wizard for Tranzda Mobile Platform <br>
* =======================================================================<br>
*/

#include "KaiXinAPICommon.h"

void* KaiXinAPI_MessageDetail_JsonParse(char *text)
{
	cJSON *json;
	cJSON *pTemp0;
	tResponseMessageDetail*  Response = new tResponseMessageDetail;
	memset(Response, 0 , sizeof(tResponseMessageDetail));

	json = cJSON_Parse(text);

	pTemp0 = cJSON_GetObjectItem(json,"ret");
	if (pTemp0)
	{
		Response->ret = pTemp0->valueint;	
	}

	//Success
	if(Response->ret == 1)
	{
		pTemp0 = cJSON_GetObjectItem(json, "uid");
		if(pTemp0)
		{
			if(pTemp0->valueint > 0)
				sprintf(Response->uid, "%d", pTemp0->valueint);
			else
				STRCPY_Ex(Response->uid, pTemp0->valuestring);
		}
		pTemp0 = cJSON_GetObjectItem(json, "n");
		if(pTemp0)
		{
			Response->n = pTemp0->valueint;
		}
		pTemp0 = cJSON_GetObjectItem(json, "msgnum");
		if(pTemp0)
		{
			Response->msgnum = pTemp0->valueint;
		}
		pTemp0 = cJSON_GetObjectItem(json, "mid");
		if(pTemp0)
		{
			if(pTemp0->valuedouble > 0)
				DoubleToChar(pTemp0->valuedouble, Response->mid);
			else
				STRCPY_Ex(Response->mid, pTemp0->valuestring);
		}
		pTemp0 = cJSON_GetObjectItem(json, "usernum");
		if(pTemp0)
		{
			Response->usernum = pTemp0->valueint;
		}
		pTemp0 = cJSON_GetObjectItem(json, "msgs");
		if(pTemp0)
		{
			int nSize1 = 0, i = 0;
			nSize1 = cJSON_GetArraySize(pTemp0);
			Response->nSize_msgs = nSize1;
			if( nSize1 != 0 )
			{
				Response->msgs = NULL;
				Response->msgs = (MessageDetail_msgs*) malloc(sizeof( MessageDetail_msgs ) * nSize1 );
				memset(Response->msgs, 0 , sizeof(MessageDetail_msgs) * nSize1 );
			}
			for ( i = 0; i < nSize1; i++ )
			{
				cJSON *Item1 = NULL, *pTemp1 = NULL;
				Item1 = cJSON_GetArrayItem(pTemp0,i);
				pTemp1 = cJSON_GetObjectItem(Item1, "flogo");
				if(pTemp1)
				{
					STRCPY_Ex(Response->msgs[i].flogo, pTemp1->valuestring);
				}
				pTemp1 = cJSON_GetObjectItem(Item1, "flogo50");
				if(pTemp1)
				{
					STRCPY_Ex(Response->msgs[i].flogo50, pTemp1->valuestring);
				}
				pTemp1 = cJSON_GetObjectItem(Item1, "mid");
				if(pTemp1)
				{
					if(pTemp1->valuedouble> 0)
						DoubleToChar(pTemp1->valuedouble, Response->msgs[i].mid);
					else
						STRCPY_Ex(Response->msgs[i].mid, pTemp1->valuestring);
				}
				pTemp1 = cJSON_GetObjectItem(Item1, "fuid");
				if(pTemp1)
				{
					STRCPY_Ex(Response->msgs[i].fuid, pTemp1->valuestring);
				}
				pTemp1 = cJSON_GetObjectItem(Item1, "fname");
				if(pTemp1)
				{
					STRCPY_Ex(Response->msgs[i].fname, pTemp1->valuestring);
				}
				pTemp1 = cJSON_GetObjectItem(Item1, "abscont");
				if(pTemp1)
				{
					STRCPY_Ex(Response->msgs[i].abscont, pTemp1->valuestring);
				}
				pTemp1 = cJSON_GetObjectItem(Item1, "ctime");
				if(pTemp1)
				{
					Response->msgs[i].ctime = pTemp1->valueint;
				}
				pTemp1 = cJSON_GetObjectItem(Item1, "strctime");
				if(pTemp1)
				{
					STRCPY_Ex(Response->msgs[i].strctime, pTemp1->valuestring);
				}

			}
		}

	}
	//Failue
	else
	{
		//pTemp0 = cJSON_GetObjectItem(json,"msg");
		//if (pTemp0)
		//{
		//	strcpy(Response->msg, pTemp0 ->valuestring);	
		//}
	}
	cJSON_Delete(json);
	return Response;
}



// 构造函数
TMessageDetailForm::TMessageDetailForm(TApplication* pApp):TWindow(pApp)
{
	//Create(APP_KA_ID_KaiXinHomePage);
}

// 析构函数
TMessageDetailForm::~TMessageDetailForm(void)
{

}

// 窗口事件处理
Boolean TMessageDetailForm::EventHandler(TApplication * pApp, EventType * pEvent)
{
	Boolean bHandled = FALSE;

	switch (pEvent->eType)
	{
	case EVENT_WinInit:
		{
			_OnWinInitEvent(pApp, pEvent);
			bHandled = TRUE;
			break;
		}

	case EVENT_WinClose:
		{
			_OnWinClose(pApp, pEvent);
			break;
		}

	case EVENT_CtrlSelect:
		{
			bHandled = _OnCtrlSelectEvent(pApp, pEvent);
			break;
		}
	default:
		break;
	}

	if (!bHandled)
	{
		bHandled = TWindow::EventHandler(pApp, pEvent);
	}

	return bHandled;
}

// 窗口初始化
Boolean TMessageDetailForm::_OnWinInitEvent(TApplication * pApp, EventType * pEvent)
{
	int iRet =0;
	tResponseMessageDetail* Response = NULL;
	iRet = KaiXinAPI_JsonParse(KX_MessageDetail, (void **)&Response);

	if( Response )
	{
		delete Response;	
	}	
	return TRUE;
}

// 关闭窗口时，保存设置信息
Boolean TMessageDetailForm::_OnWinClose(TApplication * pApp, EventType * pEvent)
{
	return TRUE;
}


// 控件点击事件处理
Boolean TMessageDetailForm::_OnCtrlSelectEvent(TApplication * pApp, EventType * pEvent)
{
	Boolean bHandled;

	bHandled = FALSE;

	switch(pEvent->sParam1)
	{
	case 0:
		{
			break;
		}
	default:
		break;
	}

	return bHandled;
}