/*!
*@FileName: KaiXinApp_RanchDetail.h
*@Author: GoZone
*@Date:
*@Log: 	Author 			Date 		Description
*
*@section Copyright
* =======================================================================<br>
*          Copyright ? 2010-2012 GOZONE <br>
*                All Rights Reserved.<br>
* The file is generated by Kaixin_Component Wizard for Tranzda Mobile Platform <br>
* =======================================================================<br>
*/

#ifndef  __KAIXINAPI_RANCHDETAIL_H__
#define  __KAIXINAPI_RANCHDETAIL_H__

#include "KaiXinAPI.h"

typedef struct
{
	char animalsid[32];
	char name[64];
	char growper[64];
	char growdesc[128];
	char status[32];
	char bproduct[32];
	int htime;
}RanchDetail_animals;

typedef struct
{
	char name[64];
	char skey[64];
	char type[32];
	int pnum;
	char pdesc[128];
	int stealed;
	int htime;
}RanchDetail_products;

typedef struct
{
	int ret;
	char uid[32];
	int n;
	int pn;
	char szCash[64];
	int cash;
	char ranktip[64];
	int tcharms;
	char fuid[32];
	char flogo[256];
	char fname[64];
	int  nSize_animals;  //Save the array size by code_gen tools. 
	RanchDetail_animals*  animals;
	int  nSize_products;  //Save the array size by code_gen tools. 
	RanchDetail_products*  products;
}tResponseRanchDetail;


extern void* KaiXinAPI_RanchDetail_JsonParse(char *text);


typedef struct
{
	char uid[32 + 1];
	int ret;
	char retdesc[1024*3 + 1];
}tResponseRanchHarvest;
extern void* KaiXinAPI_RanchHarvest_JsonParse(char *text);

typedef struct
{
	char uid[32 + 1];
	int ret;
	char retdesc[1024*3 + 1];
}tResponseRanchProduct;
extern void* KaiXinAPI_RanchProduct_JsonParse(char *text);



class TRanchDetailForm : public TWindow
{
public:
	TRanchDetailForm(TApplication* pApp,Boolean bNew = TRUE);
	virtual ~TRanchDetailForm(void);
	virtual Boolean EventHandler(TApplication * appP, EventType * eventP);

private:
	Boolean _OnWinInitEvent(TApplication * pApp, EventType * pEvent);
	Boolean _OnWinClose(TApplication * pApp, EventType * pEvent);
	Boolean _OnCtrlSelectEvent(TApplication * pApp, EventType * pEvent);

private:

	tResponseRanchDetail* Response;

	Int32 nProductDetailItems; 	//存储产品详情个数
	Int32 nDetailItems; 	//存储动物详情个数
	Int32 nProductActionId[10000];//存储产品收获，或者其他动作ID
	Int32 nActionId[10000];//存储收获，或者其他动作ID
	Int32 nRanchListViewId;//存放查看好友牧场ID
	Int32 nMyRanchViewId;//返回查看我的牧场
	Boolean IsSelf;
	char Fuid[32];


	Int32	m_BackBtn;

};

#endif
